### ISSUE TITLE
Markdown Ordered Lists does not work

### ISSUE THREAD

**Issue by openHacking** [nuxtlabs/demo-blog-nuxt-content#58]
**Steps to reproduce:**
1. git clone https://github.com/nuxtlabs/demo-blog-nuxt-content.git
2. Open http://localhost:3000/blog/some-interesting-title
3. Modify the content of the article and add the following content

```js
1. First item
2. Second item
3. Third item
     1. Indented item
     2. Indented item
4. Fourth item

-First item
-Second item
-Third item
     -Indented item
     -Indented item
-Fourth item
```
4. The rendering result does not show the list sort number
![image](https://user-images.githubusercontent.com/72927208/110895537-eba61400-8334-11eb-82de-44a44a58811b.png)

**Expected result**
![image](https://user-images.githubusercontent.com/72927208/110895618-109a8700-8335-11eb-9bb4-5db664a155b5.png)

**See the video demo in detail**

https://user-images.githubusercontent.com/72927208/110895487-d3ce9000-8334-11eb-8073-2ad3f6f29ca5.mp4

**Comment by AntMam** [comment]
I had the same issue. Tailwind overrides markdown styling. You have to install @tailwindcss/typography and then add the following from [this blog post](https://zaengle.com/blog/tailwind-typography-plugin):


`// tailwind.config.js
module.exports = {
  theme: {
    // ...
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}`

And then where you want to add your markdown:

`<div class="prose">
	{{ content }}
</div>`

Hope this helps

**Comment by openHacking** [comment]
> I had the same issue. Tailwind overrides markdown styling. You have to install @tailwindcss/typography and then add the following from [this blog post](https://zaengle.com/blog/tailwind-typography-plugin):
> 
> ```
> // tailwind.config.js
> module.exports = {
>   theme: {
>     // ...
>   },
>   plugins: [
>     require('@tailwindcss/typography'),
>     // ...
>   ],
> }
> ```
> 
> And then where you want to add your markdown:
> 
> ```
> <div class="prose">
> 	{{ content }}
> </div>
> ```
> 
> Hope this helps

Thanks a lot.

But I have switched to next.js to write my blog 😂
